repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^notebooks/
      - id: ruff-format
        exclude: ^notebooks/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^notebooks/
      - id: end-of-file-fixer
        exclude: ^notebooks/
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: debug-statements
        exclude: ^notebooks/

  # Custom hook to ensure requirements.txt is updated from uv.lock
  - repo: local
    hooks:
      - id: update-requirements
        name: Update requirements.txt from uv.lock
        entry: bash -c 'uv pip compile pyproject.toml -o requirements.txt'
        language: system
        pass_filenames: false
        files: 'uv\.lock$|pyproject\.toml$'
